name: Update Stars, Pulls and Downloads From APIs

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  schedule:
    - cron: '0 8 * * 1' # Runs at 8:00 AM every Monday

jobs:
  fetchAndUpdate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Add dependencies
      run: |
        python -m pip install requests

    - name: Update files after fetching data from APIs
      run: |
        python docs/tools/vdb_table/fetch-data.py

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'Chirag Jain'
        git config --global user.email '31701616+chirag-jn@users.noreply.github.com'
        git add docs/tools/vdb_table/data/.
        git commit -m "Update Stars, Pulls & Downloads" || exit 0  # Exit 0 if no changes
        git push
